### ISSUE TITLE
No log info pushed to app.bugsnag.com

### ISSUE THREAD

**Issue by tuannars** [codereligion/bugsnag-logback#11]
Dear Mr @SierraGolf,
I tried writing a sample to test pushing log info to bugsnag.com with Eclipse IDE on my PC as below:
build.gradle
```
apply plugin: 'java

repositories {
    jcenter()
}

dependencies {
    compile 'com.google.guava:guava:23.0'
    compile 'com.google.cloud:google-cloud-datastore:1.22.0'

    compile 'commons-lang:commons-lang:2.6'

    compile 'ch.qos.logback:logback-classic:1.2.3'
    compile 'com.codereligion:bugsnag-logback:1.1.0'

    // Use JUnit test framework
    testImplementation 'junit:junit:4.12'
}

buildscript {
    repositories {
        jcenter()
    }
}

jar {
    manifest {
        attributes('Main-Class': 'com.mycom.trytest.TryLogBackBugSnag1')
    }

    from {
        configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
    }
}
```

logback.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<configuration>
 <appender name="BUGSNAG" class="com.codereligion.bugsnag.logback.Appender">
      <apiKey>{my key}</apiKey>
      <releaseStage>staging</releaseStage>
      <notifyReleaseStages>staging,production</notifyReleaseStages>
  </appender>

	<root level="debug">
		<appender-ref ref="BUGSNAG" />
	</root>

</configuration>
```

TryLogBackBugSnag1.java
```
package com.mycom.trytest;

import org.slf4j.LoggerFactory;

import ch.qos.logback.classic.Logger;

public class TryLogBackBugSnag1 {

	private static Logger logger = (Logger) LoggerFactory.getLogger(TryLogBackBugSnag1.class);

	public static void main(String[] args) {
		logger.warn("com.mycom.trytest.TryLogBackBugSnag1: warning test 1");
		logger.info("com.mycom.trytest.TryLogBackBugSnag1: info test 2");
		logger.debug("com.mycom.trytest.TryLogBackBugSnag1: debug test 3");
		logger.error("com.mycom.trytest.TryLogBackBugSnag1: error test 4");
	}
}
```

When run TryLogBackBugSnag1.java, i met the log info in the console of Eclipse IDE:
```
SLF4J: A number (2) of logging calls during the initialization phase have been intercepted and are
SLF4J: now being replayed. These are subject to the filtering rules of the underlying logging system.
SLF4J: See also http://www.slf4j.org/codes.html#replay
```
and there is no log info pushed to the https://app.bugsnag.com/xxxxx

Can you tell me what i am doing wrong?

Thank you!

Tuan

**Comment by SierraGolf** [comment]
Hey man,

I haven't been doing any work on this project in years.
I would suggest you check if the original api that it was implemented against is still active or if it has been decommissioned and thus the appender is not working anymore.

You can also use something like charles proxy to see whats happening to the actual requests.

Cheers!
Sebastian

**Comment by tuannars** [comment]
Thanks Mr SierraGolf!
I will retry with your suggestion.

Best regards!
Tuan

**Comment by tuannars** [comment]
Dear Mr @SierraGolf,
I retried in debugging mode and saw when logback-bugsnag calls the function append(final ILoggingEvent event):

```
com.codereligion.bugsnag.logback
...
public class Appender extends AppenderBase<ILoggingEvent> {

@Override
    protected void append(final ILoggingEvent event) {

        if (!isStarted() || configuration.isStageIgnored() || shouldNotNotifyFor(event)) {
            return;
        }

        final NotificationVO notification = converter.convertToNotification(event);
        sender.send(notification);
    }
    //....
}
```
then returns and cannot  call next function
`sender.send(notification); `
because when calls shouldNotNotifyFor(event)), the even do not contain a ThrowableProxy.
This maybe caught there is not error log sent to https://app.bugsnag.com/xxxxx
Why do you check the condition? 
So with the condition, ch.qos.logback.classic.Logger.error(String msg) cannot notify error log to bugsnag 
Could you please explain for me? 

Thank you!

Tuan

**Comment by SierraGolf** [comment]
Hey Tuan,

yeah that is an easy one. The thing was designed to only forward exceptions being logged.
So basically if there is no ThrowableProxy, it means the log does not contain an exception.

Cheers!
Sebastian

**Comment by tuannars** [comment]
Thanks Mr SierraGolf!

Tuan
