### ISSUE TITLE
Requires javax >= 2.0

### ISSUE THREAD

**Issue by Donnotron666** [codereligion/bugsnag-logback#5]
Sender has a dependency on javax 2.0, which isn't possible in my project. I'd like to be able to sub-in a new Sender type, but the private constructors and final-everything make that impossible. Instead I've had to build a new appender and sender just so I can cast the Response on Sender.java:122 to a ClientResponse.

**Comment by SierraGolf** [comment]
Sorry, but I do not completely understand your problem. 

1. I don't understand what you mean by "javax 2.0"? Please state exactly which dependency gives you problems and why (e.g. by stating with which other dependency it conflicts).
2. In case you have a problem with jaxrs and its implementation (resteasy), would it help if you could swap-out the jaxrs implementation for something else than resteasy, e.g. jersey?
3. [Sender.java:122](https://github.com/codereligion/bugsnag-logback/blob/master/src/main/java/com/codereligion/bugsnag/logback/Sender.java#L122) does not seem like the place where need to do a cast. Why exactly do you need to cast the response to ```ClientResponse```?

**Comment by SierraGolf** [comment]
closing this, because there was no response from OP in 2 years.
